version: "3.7"
services:
  app:
    container_name: "server"
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
    volumes:
      - server-api:/app
    restart: always
    networks:
      - api
  database:
    container_name: "database"
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - database-api:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: final_project_uas
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    networks:
      - api

volumes:
  server-api:
  database-api:

networks:
  api:
    driver: bridge
